version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - go-pkg:/go/pkg
    command: sleep infinity
    network_mode: service:db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/dev
      - GO_ENV=development
    
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
    ports:
      - 5432:5432

volumes:
  postgres-data:
  go-pkg: